### ISSUE TITLE
How to protect project?

### ISSUE THREAD

**Issue by DemonMartin** [LockBlock-dev/pkg-unpacker#5]
Any Idea how I can protect my packaged project, so it cannot be "unpacked"?
(besides obfuscating the main code)

**Comment by LockBlock-dev** [comment]
By default pkg generates V8 bytecode instead of including the source code in the executable. I'm not aware of other ways to protect your app, you should try to ask directly on the [vercel/pkg repository](https://github.com/vercel/pkg).
